export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
export const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";
export const SET_DIRECT_MESSAGES_USERS = "SET_DIRECT_MESSAGES_USERS";
export const SET_USER_POSTS = "SET_USER_POSTS";
export const SET_CHANNEL_MESSAGES = "SET_CHANNEL_MESSAGES";
